E_Commerse/urls.py

from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from .import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('base/', views.BASE, name='base'),

    path('', views.HOME, name='home'),
    path('product/<slug:slug>',views.PRODUCT_DETAILS, name='product_detail'),

    # account URL
    path('account/my-account',views.MY_ACCOUNT, name='my_account'),
    path('account/register',views.REGISTER, name='register'),
    path('account/login',views.LOGIN, name='login'),
    path('account/logout',views.logout, name='logout'),
    path('account/profile',views.PROFILE, name='profile'),
    path('checkout',views.CHECKOUT, name='checkout'),
    path('order', views.ORDER, name='orders'),
    path('account/ErrorPage', views.ERROR, name='ErrorPage'),

    # URL for Cart
    path('cart/add/<int:id>/', views.cart_add, name='cart_add'),
    path('cart/item_clear/<int:id>/', views.item_clear, name='item_clear'),
    path('cart/item_increment/<int:id>/',
         views.item_increment, name='item_increment'),
    path('cart/item_decrement/<int:id>/',
         views.item_decrement, name='item_decrement'),
    path('cart/cart_clear/', views.cart_clear, name='cart_clear'),
    path('cart/cart-detail/',views.cart_detail,name='cart_detail'),

    # Other Page Url
    path('product', views.PRODUCT,name='product'),
    path('product/filter-data',views.filter_data,name="filter-data"),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Website/models.py
from django.contrib.auth.models import User
from django.db import models
from ckeditor.fields import RichTextField
from django.utils.text import slugify
from django.db.models.signals import pre_save
import datetime


# Create your models here.
class Slider(models.Model):
    DISCOUNT_DEAL = (
        ('HOT DEALS', 'HOT DEALS'),
        ('New Arrivals', 'New Arrivals'),
    )

    Image = models.ImageField(upload_to='media\slider_imgs')
    Discount_Deal = models.CharField(choices=DISCOUNT_DEAL, max_length=100)
    Sale = models.IntegerField()
    Brand_Name = models.CharField(max_length=200)
    Discount = models.IntegerField()
    link = models.CharField(max_length=200)

    def __str__(self):
        return self.Brand_Name


class banner(models.Model):
    image = models.ImageField(upload_to='media\slider_imgs')
    Discount_Deal = models.CharField(max_length=100)
    Quote = models.CharField(max_length=200)
    Discount = models.IntegerField()
    link = models.CharField(max_length=200, null=True)

    def __str__(self):
        return self.Quote


class Main_Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Category(models.Model):
    main_category = models.ForeignKey(Main_Category, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name + '__' + self.main_category.name


class Sub_Category(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)

    def __str__(self):
        # return self.name+ '__'+ self.category.name
        return self.category.main_category.name + '__' + self.category.name + '--' + self.name


class Section(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Product(models.Model):
    total_quantity = models.IntegerField()
    Availability = models.IntegerField()
    featured_image = models.CharField(max_length=100)
    product_name = models.CharField(max_length=100)
    price = models.IntegerField()
    Discount = models.IntegerField()
    Product_information = RichTextField()
    model_Name = models.CharField(max_length=100)
    Categories = models.ForeignKey(Category, on_delete=models.CASCADE)
    Tags = models.CharField(max_length=100)
    Description = RichTextField()
    section = models.ForeignKey(Section, on_delete=models.DO_NOTHING)
    slug = models.SlugField(default='', max_length=500, null=True, blank=True)

    def __str__(self):
        return self.product_name

    def get_absolute_url(self):
        from django.urls import reverse
        return reverse("product_detail", kwargs={'slug': self.slug})

    class Meta:
        db_table = "app_Product"

    @staticmethod
    def get_products_by_id(ids):
        return Product.objects.filter(id__in=ids)


def create_slug(instance, new_slug=None):
    slug = slugify(instance.product_name)
    if new_slug is not None:
        slug = new_slug
    qs = Product.objects.filter(slug=slug).order_by('-id')
    exists = qs.exists()
    if exists:
        new_slug = "%s-%s" % (slug, qs.first().id)
        return create_slug(instance, new_slug=new_slug)
    return slug


def pre_save_post_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)


pre_save.connect(pre_save_post_receiver, Product)


class Product_Image(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    Image_url = models.CharField(max_length=200)


class Additional_Information(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    specification = models.CharField(max_length=100)
    detail = models.CharField(max_length=100)

# For the order Detail Page
class Order(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, default=1)
    #user = models.ForeignKey(User, on_delete=models.CASCADE)
    user =models.CharField(max_length=50, default='', blank=True)
    quantity = models.IntegerField(default=1)
    price = models.IntegerField(default=50)
    address = models.CharField(max_length=50, default='', blank=True)
    phone = models.CharField(max_length=50, default='', blank=True)
    Email = models.CharField(max_length=50, default='', blank=True)
    date = models.DateField(default=datetime.datetime.today)

    def placeOrder(self):
        self.save()

    @staticmethod
    def get_orders_by_user(email):
        return Order.objects.filter(email=email).order_by('-date')

templates/includes/footer.html
 <!-- footer-start -->
    <footer>
        <div class="fotter-area d-dark-bg">
            <div class="footer__top pt-80 pb-15">
                <div class="container">
                    <div class="row">
                        <div class="col-xl-5 col-lg-4 order-last-md">
                            <div class="row">
                                <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-6">
                                    <div class="footer__widget">
                                        <div class="footer__widget-title">
                                            <h4>Customer Care</h4>
                                        </div>
                                        <div class="footer__widget-content">
                                            <div class="footer__link">
                                                <ul>
                                                    <li><a href="faq.html">How to use Account</a></li>
                                                    <li><a href="faq.html">Payment Methods</a></li>
                                                    <li><a href="faq.html">Delivery &amp; Dispatch</a></li>
                                                    <li><a href="faq.html">Problems with Order</a></li>
                                                </ul>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-6">
                                    <div class="footer__widget">
                                        <div class="footer__widget-title">
                                            <h4>Customer Service</h4>
                                        </div>
                                        <div class="footer__widget-content">
                                            <div class="footer__link">
                                                <ul>
                                                    <li><a href="faq.html">Help Center</a></li>
                                                    <li><a href="faq.html">Contact Us</a></li>
                                                    <li><a href="faq.html">Terms and Conditions</a></li>
                                                    <li><a href="faq.html">Policies &amp; Rules</a></li>
                                                </ul>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-xl-7 col-lg-8 order-first-md">
                            <div class="footer__top-left">
                                <div class="row">

                                    <div class="col-xl-7 col-lg-6 col-md-6 col-sm-6">
                                        <div class="row">

                                        <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6">
                                    <div class="footer__widget">
                                        <div class="footer__widget-title">
                                            <h4>Quick Links</h4>
                                        </div>
                                        <div class="footer__widget-content">
                                            <div class="footer__link">
                                                <ul>
                                                    <li><a href="my-account.html">My account</a></li>
                                                    <li><a href="faq.html">FAQs</a></li>
                                                </ul>
                                            </div>
                                        </div>
                                    </div>
                                </div></div>
                                    </div><div class="col-xl-5 col-lg-6 col-md-6 col-sm-6">
                                        <div class="footer__widget">
                                            <div class="footer__widget-title mb-20">
                                                <h4>About This Website</h4>
                                            </div>
                                            <div class="footer__widget-content">
                                                <p class="footer-text mb-35">This is E-Commerse Website where you can buy any product </p>
                                                <div class="footer__hotline d-flex align-items-center mb-10">
                                                    <div class="text">
                                                        <h4>Got Question? Call us 24/7!</h4>
                                                        <span><a href="tel:100-123-456-7890">+91 123456789</a></span>
                                                    </div>
                                                </div>
                                                <div class="footer__info">
                                                    <ul>
                                                        <li>
                                                            <span>Add:  <a target="_blank">Noida, UP, India</a></span>
                                                        </li>
                                                    </ul>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!-- footer-end -->

templates/includes/header.html
{% load static %}

<!-- header-start -->
   <header class="header d-blue-bg">
       <div class="header-top">
           <div class="container">
               <div class="header-inner">
                   <div class="row align-items-center">
                       <div class="col-xl-6 col-lg-7">
                           {% if user.is_authenticated %}
                            Welcome:  {{user.email}}
                           Your ID: {{user.id}}
                           {% else %}
                            <h3> Please Login</h3>
                           {% endif %}
                       </div>

                   </div>
               </div>
           </div>
       </div>
       <div class="header-mid">
           <div class="container">
               <div class="heade-mid-inner">
                   <div class="row align-items-center">
                       <div class="col-xl-3 col-lg-3 col-md-4 col-sm-4">
                           <div class="header__info">
                               <div class="logo">
                                   <a href="#" class="logo-image"><img src="{% static 'assets/img/logo/logo1.jpg' %}" alt="logo"></a>
                               </div>
                           </div>
                       </div>
                       <div class="col-xl-5 col-lg-4 d-none d-lg-block">
                           <div class="header__search">
                               <form action="#">
                                   <div class="header__search-box">
                                       <input class="search-input" type="text" placeholder="I'm shopping for...">
                                       <button class="button" type="submit"><i class="far fa-search"></i></button>
                                   </div>
                                   <div class="header__search-cat">
                                       <select>
                                           <option>All Categories</option>
                                           <option>Best Seller Products</option>
                                           <option>Top 10 Offers</option>
                                           <option>New Arrivals</option>
                                           <option>Phones &amp; Tablets</option>
                                           <option>Electronics &amp; Digital</option>
                                           <option>Fashion &amp; Clothings</option>
                                           <option>Jewelry &amp; Watches</option>
                                           <option>Health &amp; Beauty</option>
                                           <option>Sound &amp; Speakers</option>
                                           <option>TV &amp; Audio</option>
                                           <option>Computers</option>
                                       </select>
                                   </div>
                               </form>
                           </div>
                       </div>
                       <div class="col-xl-4 col-lg-5 col-md-8 col-sm-8">
                           <div class="header-action">

                               <div class="block-cart action">
                                   <a class="icon-link" href="{% url 'cart_detail' %}">
                                   <i class="flaticon-shopping-bag"></i>
                                   <span class="count">{{request.session.cart|length}}</span>
                                   <span class="text">
                                   <span class="sub">Your Cart:</span>
                                   Rs.{{cart_total_amount}} </span>
                                   </a>
                               </div>

                               {% if user.is_authenticated %}
                               <div class="block-userlink">
                                   <a class="icon-link" href="{% url 'logout' %}">
                                   <i class="flaticon-user"></i>
                                   <span class="text">
                                   <span class="sub">Logout </span>
                                   My Profile </span>
                                   </a>
                               </div>
                               {% else %}
                               <div class="block-userlink">
                                   <a class="icon-link" href="{% url 'my_account' %}">
                                   <i class="flaticon-user"></i>
                                   <span class="text">
                                   <span class="sub">Login </span>
                                   My Account </span>
                                   </a>
                               </div>
                               {% endif %}

                           </div>
                       </div>
                   </div>
               </div>
           </div>
       </div>
       <div class="header__bottom">
           <div class="container">
               <div class="row g-0 align-items-center">
                   <div class="col-lg-3">
                       <div class="cat__menu-wrapper side-border d-none d-lg-block">
                           <div class="cat-toggle">
                               <button type="button" class="cat-toggle-btn cat-toggle-btn-1"><i class="fal fa-bars"></i> Shop by Categories </button>
                               <div class="cat__menu">
                                   <nav id="mobile-menu" style="display: block;">
                                       <ul>
                                           {% for i in main_category %}
                                           <li>
                                               <a href="#">{{i.name}} <i class="far fa-angle-down"></i></a>
                                               <ul class="mega-menu">
                                                   {% for cat in i.category_set.all %}
                                                   <li><a href="#">{{cat.name}}</a>
                                                       <ul class="mega-item">
                                                           {% for sub_cat in cat.sub_category_set.all %}
                                                           <li><a href="{% url 'product' %}">{{sub_cat.name}}</a></li>
                                                           {% endfor %}
                                                       </ul>
                                                   </li>
                                                   {% endfor %}

                                               </ul>
                                           </li>
                                           {% endfor %}


                                          <!-- <li><a href="shop.html">Health &amp; Beauty</a></li>-->
                                       </ul>
                                   </nav>
                               </div>
                           </div>
                       </div>
                   </div>
                   <div class="col-lg-6 col-md-6 col-3">
                     <div class="header__bottom-left d-flex d-xl-block align-items-center">
                       <div class="side-menu d-lg-none mr-20">
                         <button type="button" class="side-menu-btn offcanvas-toggle-btn"><i class="fas fa-bars"></i></button>
                       </div>
                       <div class="main-menu d-none d-lg-block">
                           <nav>
                               <ul>
                                   <li>
                                       <a href= "{% url 'home' %}"class="active">Home</i></a>

                                   </li>
                                   <li><a href="{% url 'ErrorPage' %}">About Us</a></li>

                                   <li>
                                       <a href= "{% url 'product' %}"class="active">Product</i></a>
                                   </li>

                                   <li>
                                       <a href="#">Account <i class="far fa-angle-down"></i></a>
                                       <ul class="submenu">
                                           <li><a href="my-account.html">My Account</a></li>
                                           <li><a href="{% url 'cart_detail' %}">My Cart</a></li>
                                           <li><a href="{% url 'orders' %}">My Orders</a></li>
                                           <li><a href="{% url 'ErrorPage' %}">Contact Us</a></li>
                                       </ul>
                                   </li>
                               </ul>
                           </nav>
                       </div>
                     </div>
                   </div>
                   <div class="col-lg-3 col-md-6 col-9">
                       <div class="shopeing-text text-sm-end">
                           <p>Spend Rs.2500 and get free shipping!</p>
                       </div>
                   </div>
               </div>
           </div>
       </div>
   </header>
   <!-- header-end -->


    <!-- offcanvas area start -->
   <div class="offcanvas__area">
       <div class="offcanvas__wrapper">
       <div class="offcanvas__close">
           <button class="offcanvas__close-btn" id="offcanvas__close-btn">
               <i class="fal fa-times"></i>
           </button>
       </div>
       <div class="offcanvas__content">
           <div class="offcanvas__logo mb-40">
               <a href="index.html">
               <img src="{ % static 'assets/img/logo/logo-white.png' %}" alt="logo">
               </a>
           </div>
           <div class="offcanvas__search mb-25">
               <form action="#">
                   <input type="text" placeholder="What are you searching for?">
                   <button type="submit" ><i class="far fa-search"></i></button>
               </form>
           </div>
           <div class="mobile-menu fix"></div>
           <div class="offcanvas__action">

           </div>
       </div>
       </div>
   </div>
   <!-- offcanvas area end -->
   <div class="body-overlay"></div>
   <!-- offcanvas area end -->